name: Test
'on':
  pull_request:
    branches:
    - main
    - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Get current nginx version
      run: echo "NGINX_VERSION=$(cat nginx-version)" >> $GITHUB_ENV
    - name: Build image
      run: docker buildx build . --build-arg NGINX_VERSION=${{ env.NGINX_VERSION }} -t test/nginx:latest --load
    - name: Test image
      run: |-
        docker network create test-network
        docker run --rm -d --network test-network --name nginx -p 8080:80 test/nginx:latest

        sleep 5s
        text=$(curl -s "http://localhost:8080")
        docker stop $(docker ps -q)

        if [[ $text != *"Down for Maintenance"* ]]; then
            echo "Output does not contain 'Down for Maintenance'"
            echo "$text"
            exit 1
        else
            echo "$text"
        fi
